### ISSUE TITLE
New Release to upgrade nix to 0.13.0?

### ISSUE THREAD

**Issue by mitnk** [murarth/mortal#10]
Hello,

In new versions of Rust, `nix==0.7.0` would error with `expected i32, found u64`. Maybe we can release a new mortal version to fix it.

I saw in master, `nix` already `0.13.0`, so just a new release on crates.io is needed?

Thanks in advance!

**Comment by mitnk** [comment]
Also we may need a new `linefeed` release to pair with this `mortal` release :)

**Comment by murarth** [comment]
Done and done.

The latest version of `mortal` is now 0.2.0
The latest version of `linefeed` is now 0.6.0

Thank you for the issue.

**Comment by mitnk** [comment]
Thank you!
