### ISSUE TITLE
Could not find `termios` in `sys` when cross compiling for aarch64-apple-ios

### ISSUE THREAD

**Issue by akatasonov** [murarth/mortal#5]
I'm cross compiling a project that uses mortal v0.1.5 as a dependency for aarch64-apple-ios and the compilation fails with:

23 | use nix::sys::termios::{
   |               ^^^^^^^ could not find `termios` in `sys`
As far as I can tell nix does support aarch64. Is this a bug or some misconfiguration on my end?

**Comment by murarth** [comment]
No, this issue is my fault. `mortal` is using an old version of `nix`, in which `termios` is not defined on the `ios` platform.

I really should be using the current version of `nix`, but there's some weirdness in one of the `termios` APIs. I'll see what I can do about upgrading it.

**Comment by murarth** [comment]
Okay, I've upgraded to the latest version of `nix`. This should solve this issue. Let me know if everything is working as expected.

**Comment by akatasonov** [comment]
Yes, it solves the problem. Thanks!!
